#echo "Mise à jour de la codification"
#bin/console app:update-codification-ref
VERSION="2027"

echo "Mise  à jour des référentiels de compétences"
bin/console app:genere-ref-competence GEA "$VERSION"
#bin/console app:genere-ref-competence GEII "$VERSION"
#bin/console app:genere-ref-competence GMP "$VERSION"
#bin/console app:genere-ref-competence TC "$VERSION"
#bin/console app:genere-ref-competence CJ "$VERSION"
#bin/console app:genere-ref-competence CS "$VERSION"
#bin/console app:genere-ref-competence Info-Com "$VERSION"
#bin/console app:genere-ref-competence Chimie "$VERSION"
#bin/console app:genere-ref-competence GB "$VERSION"
#bin/console app:genere-ref-competence GCGP "$VERSION"
#bin/console app:genere-ref-competence GCCD "$VERSION"
#bin/console app:genere-ref-competence INFO "$VERSION"
#bin/console app:genere-ref-competence MP "$VERSION"
#bin/console app:genere-ref-competence MT2E "$VERSION"
#bin/console app:genere-ref-competence MMI "$VERSION"
#bin/console app:genere-ref-competence GACO "$VERSION"
#bin/console app:genere-ref-competence PEC "$VERSION"
#bin/console app:genere-ref-competence QLIO "$VERSION"
#bin/console app:genere-ref-competence MLT "$VERSION"
#bin/console app:genere-ref-competence STID "$VERSION"
#bin/console app:genere-ref-competence GIM "$VERSION"
#bin/console app:genere-ref-competence HSE "$VERSION"
#bin/console app:genere-ref-competence RT "$VERSION"
#bin/console app:genere-ref-competence SGM "$VERSION"
echo "Fin  de la mise  à jour des référentiels de compétences"
