monolog:
    handlers:
        main:
            type:           rotating_file
            excluded_http_codes: [404, 405]
            max_files:      365
            path:           "%kernel.logs_dir%/%kernel.environment%.all.log"
            level:          info

        login:
            type:           rotating_file
            max_files:      365
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       security

        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      10
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info

        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
            excluded_http_codes: [404, 405]
        grouped_critical:
            type:           group
            members:        [streamed_critical] #, buffered_critical]
        streamed_critical:
            type:           rotating_file
            max_files:      10
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          info
